#+TITLE: Henrique's laboratory book
#+AUTHOR: Henrique Silva
#+email: hcpsilva@inf.ufrgs.br
#+INFOJS_OPT:
#+PROPERTY: session *R*
#+PROPERTY: cache yes
#+PROPERTY: results graphics
#+PROPERTY: exports both
#+PROPERTY: tangle yes

For now this is only a scratch, as I'm still reading up others Emacs configs and
setting up my [[https://github.com/hcpsilva/dotfiles][mobile]] Linux environment.

* Journal

Here I'll write my daily tasks and to-dos so I can keep track of what I'm doing.

** To-do

*Active items*:
- [ ] set up my table
- [ ] do the second experiment of schnorr/par

*Finished items*:

** Daily

** Meetings

This could stay inside its respective entry in the daily journal, but I think
that separating meetings from the dailies is better.

*** 2019-04-30 Tips for ORG-Mode                                     :ATTACH:
    :PROPERTIES:
    :Attachments: init.org
    :ID:       428b174d-ec00-474e-b65c-cc8671da1019
    :END:

See the attached file in
[[./data/42/8b174d-ec00-474e-b65c-cc8671da1019/init.org]], or follow the update
instructions [[http://mescal.imag.fr/membres/arnaud.legrand/misc/init.php][here]] that points to the [[https://app-learninglab.inria.fr/gitlab/learning-lab/mooc-rr-ressources/blob/master/module2/ressources/emacs_orgmode.org][learninglab]].

* External resources

Here I'll categorize useful resources I've found while "aggressively" googling
and/or reading papers and other documents.

** Programming

** Research methodology

* Project schedule

Here is the intended project schedule to me:

| Atividade               | Maio | Junho | Julho |
|-------------------------+------+-------+-------|
| Estado da arte / StarPU | x    | x     |       |
| Experimentação          | x    | x     |       |
| Análise de desempenho   |      | x     | x     |
| Redação do relatório    |      |       | x     |
