#+TITLE: Henrique's laboratory book
#+AUTHOR: Henrique Silva
#+email: hcpsilva@inf.ufrgs.br
#+INFOJS_OPT:
#+PROPERTY: session *R*
#+PROPERTY: cache yes
#+PROPERTY: results graphics
#+PROPERTY: exports both
#+PROPERTY: tangle yes

For now this is only a scratch, as I'm still reading up others Emacs configs and
setting up my [[https://github.com/hcpsilva/dotfiles][mobile]] Linux environment.

* Journal

Here I'll write my daily tasks and to-dos so I can keep track of what I'm doing.

** To-do

*Active items*:
- [ ] set up my table
- [ ] do the first experiment of schnorr/par

*Finished items*:
- [X] set up the computer

** Daily

Here will lie my daily thoughts and daily happenings.

*** 2019-05-02

Today the day was basically dedicated to formatting and installing my distro in
my new computer. It has a 4:3 screen, which will surely be kinda funny to work
with. Also my computer only have one analog video entry and 2 displayports, for
some reason.

Anyway, I also researched and learned a lot about =ssh= while I was trying to
get my public key into =portal.inf.ufrgs.br=. With Pablo's and Jean's help I
fixed the permissions of my home directory in the server (the =$HOME= directory
needs the 700 permission to work with =ssh=! Probably someone messed up a few
years back when they created my user).

Tomorrow I'll finish the setting-up ordeal, I hope.

** Meetings

This could stay inside its respective entry in the daily journal, but I think
that separating meetings from the dailies is better.

*** 2019-04-30 Tips for ORG-Mode                                     :ATTACH:
    :PROPERTIES:
    :Attachments: init.org
    :ID:       428b174d-ec00-474e-b65c-cc8671da1019
    :END:

See the attached file in
[[./data/42/8b174d-ec00-474e-b65c-cc8671da1019/init.org]], or follow the update
instructions [[http://mescal.imag.fr/membres/arnaud.legrand/misc/init.php][here]] that points to the [[https://app-learninglab.inria.fr/gitlab/learning-lab/mooc-rr-ressources/blob/master/module2/ressources/emacs_orgmode.org][learninglab]].

* External resources

Here I'll categorize useful resources I've found while "aggressively" googling
and/or reading papers and other documents.

** Programming

** Research methodology

* Project schedule

Here is the intended project schedule to me:

| Atividade               | Maio | Junho | Julho |
|-------------------------+------+-------+-------|
| Estado da arte / StarPU | x    | x     |       |
| Experimentação          | x    | x     |       |
| Análise de desempenho   |      | x     | x     |
| Redação do relatório    |      |       | x     |
