#+TITLE: Henrique's laboratory book
#+AUTHOR: Henrique Silva
#+email: hcpsilva@inf.ufrgs.br
#+INFOJS_OPT:
#+PROPERTY: session *R*
#+PROPERTY: cache yes
#+PROPERTY: results graphics
#+PROPERTY: exports both
#+PROPERTY: tangle yes

For now this is only a scratch, as I'm still reading up others Emacs configs and
setting up my [[https://github.com/hcpsilva/dotfiles][mobile]] Linux environment.

* Journal

Here I'll write my daily tasks and to-dos so I can keep track of what I'm doing.

** To-do

*Active items*:
- [ ] set up my table
- [ ] do the first experiment of schnorr/par

*Finished items*:
- [X] set up the computer

** Daily

Here will lie my daily thoughts and daily happenings.

*** 2019-05-02

Today the day was basically dedicated to formatting and installing my distro in
my new computer. It has a 4:3 screen, which will surely be kinda funny to work
with. Also my computer only have one analog video entry and 2 displayports, for
some reason.

Anyway, I also researched and learned a lot about =ssh= while I was trying to
get my public key into =portal.inf.ufrgs.br=. With Pablo's and Jean's help I
fixed the permissions of my home directory in the server (the =$HOME= directory
needs the 700 permission to work with =ssh=! Probably someone messed up a few
years back when they created my user).

Tomorrow I'll finish the setting-up ordeal, I hope.

*** 2019-05-03 StarPU Hello World Examples                            :LUCAS:
**** Install preliminary software
***** spack

See https://github.com/spack/spack to do:

#+begin_src shell :results output
git clone https://github.com/spack/spack.git
source spack/share/spack/setup-env.sh
spack find
#+end_src

***** starpu with spack

#+begin_src shell :results output
spack info starpu
#+end_src

Verify options, then:

#+begin_src shell :results output
spack install starpu@master~cuda~examples~fast+fortran+fxt+mlr~mpi~nmad~opencl~openmp+poti+shared~simgrid~simgridmc~verbose
#+end_src

This might take some time, do it in the cluster.

Confirm the location of where starpu has been installed

#+begin_src shell :results output
spack location -i starpu
#+end_src

**** StarPU client code of two examples

There are two examples:
- ~programa.c~ (simple one-task hello world)
- ~vector_scal.c~ (multiply a vector by a scalar in parallel)

See contents in [[./src/starpu-hello-world/]].

Please note that we are using CMake to find the StarPU libraries.

The, do the following steps (try to understand each one).

Make sure you have ~spack~ in your ~PATH~ variable before going forward.

#+begin_src shell :results output
cd src/starpu-hello-world
mkdir -p build
cd build
cmake -DSTARPU_DIR=$(spack location -i starpu) ..
make
#+end_src

You'll have two binaries: ~programa~ and ~vector_scal~.

Verify that they have the correct libraries linked with ~ldd~.

Run both by launching these binaries in your CLI.

** Meetings

This could stay inside its respective entry in the daily journal, but I think
that separating meetings from the dailies is better.

*** 2019-04-30 Tips for ORG-Mode                                     :ATTACH:
    :PROPERTIES:
    :Attachments: init.org
    :ID:       428b174d-ec00-474e-b65c-cc8671da1019
    :END:

See the attached file in
[[./data/42/8b174d-ec00-474e-b65c-cc8671da1019/init.org]], or follow the update
instructions [[http://mescal.imag.fr/membres/arnaud.legrand/misc/init.php][here]] that points to the [[https://app-learninglab.inria.fr/gitlab/learning-lab/mooc-rr-ressources/blob/master/module2/ressources/emacs_orgmode.org][learninglab]].

* External resources

Here I'll categorize useful resources I've found while "aggressively" googling
and/or reading papers and other documents.

** Programming

** Research methodology

* Project schedule

Here is the intended project schedule to me:

| Atividade               | Maio | Junho | Julho |
|-------------------------+------+-------+-------|
| Estado da arte / StarPU | x    | x     |       |
| Experimentação          | x    | x     |       |
| Análise de desempenho   |      | x     | x     |
| Redação do relatório    |      |       | x     |
