#+AUTHOR: HCPSILVA

#+STARTUP: overview indent
#+LANGUAGE: pt-br
#+OPTIONS: H:3 creator:nil timestamp:nil skip:nil toc:nil num:t ^:nil ~:~
#+OPTIONS: author:nil title:nil date:nil
#+TAGS: noexport(n) deprecated(d) ignore(i)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+DESCRIPTION: Proposta de Projeto de Pesquisa INF/UFRGS para Petrobras
#+KEYWORDS: inf ufrgs petrobras

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,12pt,portuguese]
#+Latex_HEADER: \usepackage[portuguese]{babel}
#+LATEX_HEADER: \usepackage{palatino}
#+LATEX_HEADER: \usepackage{tabularx}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{multirow}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage[margin=1cm,top=0cm,bottom=4cm]{geometry}
#+Latex_HEADER: \usepackage[utf8]{inputenc}
#+Latex_HEADER: \usepackage[rubberchapters,clearempty,pagestyles]{titlesec}
#+Latex_HEADER: \usepackage{xspace}
#+latex_header: \usepackage{hyperref}
#+latex_header: \usepackage{fancyhdr}

* Contents                                                           :ignore:
** Header                                                           :ignore:

#+BEGIN_EXPORT latex
\setlength{\headheight}{3cm}
\titlespacing*{\section}{0pt}{10pt}{-.3\parskip}
\setlength{\parskip}{3pt}

\pagestyle{fancyplain}

\chead{}
\rhead{}
\lhead{UFRGS -- Departamento de Informática Aplicada \\
Prof. Lucas M. Schnorr -- http://www.inf.ufrgs.br/{\raise.17ex\hbox{$\scriptstyle\sim$}}schnorr/}
#+END_EXPORT
** Title                                                            :ignore:

#+Latex: {\Large

#+BEGIN_CENTER
Programa de Iniciação Científica da UFRGS -- 2019/2020
#+END_CENTER

#+BEGIN_CENTER
-- Relatório de Atividades do Bolsista --

*Investigação e Aprendizado de Ferramentas para*

*Boas Práticas de Experimentos Computacionais*

#+latex: {\normalsize

Bolsista: Henrique Corrêa Pereira da Silva (Cartão 262508)

Orientador: Prof. Dr. Lucas Mello Schnorr (Cartão 131748)

Período: 01/08/2019 -- 30/11/2019

#+latex: }
#+END_CENTER

#+Latex: }

** Contexto e apresentação do problema

Atualmente toda e qualquer área da ciência produz uma enorme
quantidade de dados. Na Ciência da Computação, por exemplo, ao
construir um modelo do comportamento de um bloco de código, se faz
necessário coletar milhares de medições de tempos de execução em
experimentos que são potencialmente difíceis de controlar totalmente
devido a variabilidade natural do sistema. Frequentemente, a
reprodutibilidade dos resultados científicos é comprometida devido ao
pouco controle sobre as variáveis que interferem o fenômeno sob
investigação e ao manejo inadequado dos resultado experimentais.

Os alicerces da reprodutibilidade dos resultados cientificos são
qualidade e amplidade dos dados brutos coletados e a posterior análise
dos mesmos.  No primeiro ponto, sobre qualidade e amplitude, o
problema principal é na transformação de dados que deve ser feita para
levá-los até uma situação onde a análise pode acontecer. Isso envolve
a limpeza dos dados, como por exemplo, a decisão do que fazer sobre
observações incompletas, o que fazer quando medições ficam fora de
parâmetro, etc. O universo de problemas que pode aparecer e que são
suscetíveis a limpeza é bastante grande. O problema do segundo ponto
diz respeito na escolha da melhor metodologia de análise para um
conjunto de dados, ou seja, na definição da sequência de passos que
deve ser realizado para produzir uma informação sucinta e útil que
permita tomada de decisão.

** Objetivos

O objetivo da investigação a ser realizada pelo bolsista consiste em
explorar e incorporar boas práticas a serem aplicadas desde o projeto
e subsequente realização de experimentos computacionais em ambientes
de alto desempenho até a transformação e análise dos dados para
posterior apresentação. As estratégias a serem estudadas são
estruturadas em (1) *controle e coleta* referente ao controle de
ambientes computacionais de alto desempenho baseados em Linux,
avaliação do comportamento de aplicações paralelas híbridas, e
elaboração de projeto experimental para realização de experimentos; e
(2) *análise de dados* referente ao emprego de ferramentas modernas de
análise em linguagem R com apoio em conceitos de programação
literária.

** Relatório de atividades

O bolsista de iniciação científica trabalhou em temas diversos, todos
relacionados ao projeto no que diz respeito ao aprendizado de boas
práticas de experimentos computacionais. Abaixo são dados detalhes a
respeito de um estudo de caso de análise de uma aplicação paralela
escrita em OpenMP para a fatorização QR de matrizes densas, do emprego
de princípios da programação literária para condução dos experimentos
e análise dos dados, e do emprego de conhecimentos a respeito de
projeto experimental para planejamento de quais experimentos devem ser
realizados para alcançar o máximo de informação com o menor esforço.

#+begin_comment

TODO:
- Escreva o relatório aqui, nas seções abaixo.
- Crie outras seções caso aches pertinente.

#+end_comment

*** Estudo de Caso: Fatoração QR densa

Como plataforma para a aplicação dos princípios e disciplinas citados
na introdução e contextualização, foi realizado o estudo de
implementações de uma fatoração QR que utiliza as APIs do OpenMP e da
ferramenta StarPU para paralelizar seu processamento. O estudo foi
baseado em um trabalho previamente conduzido pelo grupo de pesquisa
\cite{miletto2019abrest}, que analisava o impacto dos diferentes
/runtimes/ de programação paralela baseada em tarefas no desempenho das
aplicações.

O trabalho debruçou-se sobre essa questão utilizando como seu estudo
de caso uma fatoração QR de matriz densa. Tal operação, assim como
muitas outras operações de decomposição de matrizes, é amplamente
utilizada para a resolução de sistemas de equações matriciais, muito
comuns em problemas desde o processamento de imagens até transmissão
de sinais eletromagnéticos. Os resultados permitiram o bolsista
adquirir conhecimentos a respeito da como conduzir experimentos no
Parque Computacional de Alto Desempenho (PCAD) do Grupo de
Processamento Paralelo e Distribuído do Instituto de Informática, cujo
site é http://gppd-hpc.inf.ufrgs.br/. Nas subseções seguintes são
relatados os conhecimentos adquiridos e demais resultados.

*** Organização do Trabalho com Caderno de Anotações

Para organização de uma análise do estudo conduzido, a nossa abordagem
utilizou princípios da programação literária \cite{knuth1984} através
da tecnologia chamada /org-mode/ \cite{dominik2010}, muito semelhante à
linguagem /markdown/ amplamente conhecida. Intercalando a prosa e a
programação para alcançar um estudo sistemático e reprodutível do
assunto em questão. Utilizamos o editor de texto Emacs
\cite{stallman2017emacs}, que fornece suporte e facilidade de uso
desde /org-mode/ até a execução remota através da ferramenta /SSH/. Esse
aspecto foi materializado através do emprego de um caderno de
anotações (/Laboratory Notebook/) frequentemente identificado por
/LabBook/. O versionamento de tal documento e da base de código a partir
dele escrita foi realizada através da ferramenta distribuída de
versionamento /git/ \cite{stanisic2015}, permitindo, assim, fácil
revisão pelo orientador do trabalho realizado pelo bolsista.

Dessa maneira, listamos e definimos como objetivo algumas possíveis
extensões do estudo da fatoração QR densa, a fim de explorar detalhes
diferentes daqueles do escopo inicial desse estudo. Para isso, foi
empregado um esforço grande na reprodução dos resultados obtidos,
processo que contou com o reforço e incremento da documentação já
presente no trabalho e com a criação de procedimentos para facilitar a
reprodução da maneira que coletamos os dados. O aprendizado adquirido
neste processo é de suma importância para a continuidade do bolsista
em qualquer área de investigação científica.

*** Planejamento e Execução do Projeto Experimental

Na criação dos projetos experimentais para a replicação dos
experimentos já existentes do estudo de caso utilizamos uma abordagem
de fatorial completo \cite{jain1990art} sempre que possível, a fim de
analisar os efeitos da combinação de todos os fatores em análise. No
entanto, tal abordagem nem sempre foi seguida, dado o grande custo
computacional de certas combinações dos fatores analisados, como o
tamanho do bloco da computação e o tamanho total da matriz. Sendo
assim, foram retirados do projeto as combinações que levavam a uma
grande quantidade de tarefas sendo criadas, já que, quando em excesso,
levavam a uma grande sobrecarga (/overhead/) no tempo de execução,
sobrecarga esta dedicada à gerência dessa grande quantidade de
tarefas. Essa escolha foi tomada levando em conta a necessidade de,
além do exercício de criação de projetos experimentais, exercitar
também a análise e apresentação de dados coletados nesses
processos. Claro, ao realizar a retirada de certas configurações de
teste, o processo era documentado e justificado, além de planejados
futuros experimentos que complementariam essas faltas executando o
projeto original completo.

Essencial em qualquer processo experimental, foram tomados cuidados
especiais para que as dependências para a execução da base de código
fossem obtidas e instaladas, o que auxilia no processo de reprodução
dos /scripts/ experimentais. Dito isso, alcançamos esse objetivo através
da ferramenta de distribuição de pacotes /Spack/
\cite{gamblin2015spack}, que opera sem necessitar de direitos de
superusuário (/root/). Isso é essencial para a execução em ambientes
controlados como /clusters/ de alto desempenho.  Tais preocupações são,
cada vez mais, de grande importância na produção de quaisquer
artefatos científicos \cite{stanisic2015}, principalmente na área da
computação, como previamente citado na motivação desse
trabalho. Garantidas quaisquer dependências, os projetos experimentais
foram executados no /cluster/ de alto desempenho do grupo
\cite{nesi2019pcad}, gerenciado utilizando a ferramenta /Slurm/
\cite{yoo2003slurm}. Os experimentos foram, dessa maneira, realizados
de maneira a reduzir a influência da variabilidade natural de sistemas
computacionais.

** Conclusão

Tendo em vista o trabalho realizado ao longo dos últimos quatro meses,
o bolsista foi capaz de incorporar a metodologia de trabalho adotado
no grupo de pesquisa, através do aprendizado de ferramentas tais como
/org-mode/ \cite{dominik2010}, Emacs \cite{stallman2017emacs}, /git/
\cite{stanisic2015}, conceitos de projeto fatorial completo
\cite{jain1990art} gerados na linguagem R, /Spack/
\cite{gamblin2015spack} e /Slurm/ \cite{yoo2003slurm}. Além disso, o
bolsista codificou inúmeros /scripts/ para realização dos experimentos e
se dedicou na verificação e validação de resultados previamente
obtidos, dentro da metodologia de investigação científica moderna.

Do ponto de vista do projeto inicialmente delineado e proposto, o
aluno atendeu as atividades 1. Estudo de fatores, 2. Controle, Coleta
e Projeto Experimental, 3. Aplicação Paralela, 4. Ferramentas de
Análise de Dados, e 5. Estudo de Caso, atividades previstas para os
primeiros quatro meses de execução do projeto. Em relação aos
objetivos do projeto, o bolsista atendeu ao objetivo de *controle e
coleta* em experimentos computacionais.

** Refs                                                             :ignore:

#+LATEX: \bibliographystyle{apalike}
#+LATEX: \bibliography{refs}

* BIBTEX file is HERE                                              :noexport:

Tangle this file with C-c C-v t; the =make= command tangle it automatically.

#+begin_src bib :tangle refs.bib
% Only BIBTEX entries here

@inproceedings{yoo2003slurm,
 author = {Yoo, Andy B. and Jette, Morris A. and Grondona, Mark},
 title = {SLURM: Simple Linux Utility for Resource Management},
 booktitle = {Job Scheduling Strategies for Parallel Processing},
 year = {2003},
 publisher = {Springer Berlin Heidelberg},
 address = {Berlin, Heidelberg},
 pages = {44--60},
 abstract = {A new cluster resource management system called Simple Linux Utility Resource Management (SLURM) is described in this paper. SLURM, initially developed for large Linux clusters at the Lawrence Livermore National Laboratory (LLNL), is a simple cluster manager that can scale to thousands of processors. SLURM is designed to be flexible and fault-tolerant and can be ported to other clusters of different size and architecture with minimal effort. We are certain that SLURM will benefit both users and system architects by providing them with a simple, robust, and highly scalable parallel job execution environment for their cluster system.},
 isbn = {978-3-540-39727-4}
}

@inproceedings{nesi2019pcad,
 author = {Lucas Leandro Nesi and Matheus S. Serpa and Lucas Mello Schnorr and Philippe Olivier Alexandre Navaux},
 title = {HPC Resources Management Infraestruture Description and 10-month Statistics},
 booktitle = {Anais do XVII Workshop de Processamento Paralelo e Distribuído},
 location = {Porto Alegre},
 year = {2019},
 keywords = {},
 issn = {0000-0000},
 pages = {21--24},
 url = {https://www.inf.ufrgs.br/gppd/wsppd/2019/papers/proceedings/WSPPDProceedings.pdf}
}

@book{jain1990art,
  title={The Art of Computer Systems Performance Analysis: Techniques for Experimental Design, Measurement, Simulation, and Modeling},
  author={Jain, R.},
  isbn={9788126519057},
  url={https://books.google.com.br/books?id=eOR0kJjgMqkC},
  year={1990},
  publisher={Wiley}
}

@inproceedings{miletto2019abrest,
 author = {Marcelo Miletto and Lucas Schnorr},
 title = {OpenMP and StarPU Abreast: the Impact of Runtime in Task-Based Block QR Factorization Performance},
 booktitle = {Anais do XX Simpósio em Sistemas Computacionais de Alto Desempenho},
 location = {Campo Grande},
 year = {2019},
 keywords = {},
 issn = {0000-0000},
 pages = {25--36},
 publisher = {SBC},
 address = {Porto Alegre, RS, Brasil},
 doi = {10.5753/wscad.2019.8654},
 url = {https://sol.sbc.org.br/index.php/wscad/article/view/8654}
}

@article{cpe4472,
author = {Garcia Pinto Vinícius and Mello Schnorr Lucas and Stanisic Luka and Legrand Arnaud and Thibault Samuel and Danjean Vincent},
title = {A visual performance analysis framework for task‐based parallel applications running on hybrid clusters},
journal = {Concurrency and Computation: Practice and Experience},
volume = {0},
number = {0},
year = 2018,
pages = {e4472},
keywords = {Cholesky, heterogeneous platforms, high‐performance computing, task‐based applications, trace visualization},
doi = {10.1002/cpe.4472},
url = {https://onlinelibrary.wiley.com/doi/abs/10.1002/cpe.4472},
eprint = {https://onlinelibrary.wiley.com/doi/pdf/10.1002/cpe.4472},
note = {Early View, check https://doi.org/10.1002/cpe.4472},
}

@article{stanisic2015,
 author = {Stanisic, Luka and Legrand, Arnaud and Danjean, Vincent},
 title = {An Effective Git And Org-Mode Based Workflow For Reproducible Research},
 journal = {SIGOPS Oper. Syst. Rev.},
 issue_date = {January 2015},
 volume = {49},
 number = {1},
 month = jan,
 year = {2015},
 issn = {0163-5980},
 pages = {61--70},
 numpages = {10},
 url = {http://doi.acm.org/10.1145/2723872.2723881},
 doi = {10.1145/2723872.2723881},
 acmid = {2723881},
 publisher = {ACM},
 address = {New York, NY, USA},
}

@article{knuth1984,
  author =   {Knuth, D. E.},
  doi =      {10.1093/comjnl/27.2.97},
  issn =     {0010-4620},
  journal =  {The Computer Journal},
  month =    2,
  number =   2,
  pages =    {97--111},
  publisher =    {Oxford University Press},
  title =    {{Literate Programming}},
  volume =   27,
  year =     1984
}

@book{dominik2010,
 author = {Dominik, Carsten},
 title = {The Org Mode 7 Reference Manual - Organize Your Life with GNU Emacs},
 year = {2010},
 isbn = {1906966087, 9781906966089},
 publisher = {Network Theory Ltd.},
}

@book{stallman2017emacs,
  address =  {Boston, USA},
  author =   {Richard Stallman and others},
  edition =  17,
  pages =    635,
  publisher =    {Free Software Foundation},
  title =    {{GNU Emacs Manual}},
  url = {https://www.gnu.org/software/emacs/manual/pdf/emacs.pdf},
  urldate =  {2017-12-04},
  year =     2017
}

@Manual{rmanual,
    title = {R: A Language and Environment for Statistical Computing},
    author = {{R Core Team}},
    organization = {R Foundation for Statistical Computing},
    address = {Vienna, Austria},
    year = {2018},
    url = {https://www.R-project.org/},
  }

@inproceedings{gamblin2015spack,
  title = {The Spack package manager: Bringing order to HPC software chaos},
  author = {Gamblin, Todd and LeGendre, Matthew and Collette, Michael R and Lee, Gregory L and Moody, Adam and de Supinski, Bronis R and Futral, Scott},
  booktitle = {High Performance Computing, Networking, Storage and Analysis, 2015 SC-International Conference for},
  pages = {1--12},
  year = {2015},
  organization = {IEEE}
}
#+end_src
* Emacs setup                                                      :noexport:
# Local Variables:
# eval: (add-to-list 'load-path ".")
# eval: (require 'ox-extra)
# eval: (ox-extras-activate '(ignore-headlines))
# End:
